### ISSUE TITLE
Make Contingency Table 1

### ISSUE THREAD

**Issue by savannahhoughtalin** [savannahhoughtalin/QMB-210--Group-1#14]

**Comment by savannahhoughtalin** [comment]
@clairejones22

**Comment by shelbypinette** [comment]
@clairejones22 notify me when you have completed

**Comment by clairejones22** [comment]
> @clairejones22 notify me when you have completed

Ok, I sorted and condensed all of the majors so they match up but am having trouble making the pivot table turn out the correct way. I am going to meet with someone tomorrow to try and figure out what is going wrong.

**Comment by clairejones22** [comment]
@shelbypinette I finished the table yesterday but just need to move it to the done section!
