### ISSUE TITLE
ppt slides

### ISSUE THREAD

**Issue by savannahhoughtalin** [savannahhoughtalin/QMB-210--Group-1#17]
@shelbypinette will put the link to edit the ppt. Also, remember to insert your chart/tables to the powerpoint. Whenever you finish with your slides, record yourself presenting and email to Clayton (Clayton.pullen@spartans.ut.edu)!

**Comment by shelbypinette** [comment]
https://docs.google.com/presentation/d/1u3XhHGBQJkYyLVUn71b3l8Y_kJ-PTqEzYdIKiayy-u0/edit?usp=sharing

**Comment by shelbypinette** [comment]
Link to the slide show, comment your emails so I can add you to help edit it.

**Comment by savannahhoughtalin** [comment]
savannah.houghtalin@spartans.ut.edu

**Comment by cpullen626** [comment]
Hey everyone, when making your videos please start by saying hello my name is

then the topic to be discussed,

then introduce the person after you

**Comment by shelbypinette** [comment]
Clayton will do the introduction of the video, I will be doing a part of the video where I describe what we have researched and why we researched it and what we hoped to find from our research.

**Comment by augustford** [comment]
Ok, Thank you!

**Comment by cpullen626** [comment]
Good job on videos for the slides! Just waiting for export!
