### ISSUE TITLE
Make frequency table x2

### ISSUE THREAD

**Issue by savannahhoughtalin** [savannahhoughtalin/QMB-210--Group-1#3]

**Comment by savannahhoughtalin** [comment]
@Kelsey-little @zwilt410 @MHenderson62 @clairejones22

**Comment by Kelsey-little** [comment]
Is this to do the same as the two separate frequency tables above, or do we need 4?

**Comment by MHenderson62** [comment]
What data should I be using for this?

**Comment by Kelsey-little** [comment]
Both tables have been completed and videos/slides posted.
