### ISSUE TITLE
Make Frequency Table 1

### ISSUE THREAD

**Issue by savannahhoughtalin** [savannahhoughtalin/QMB-210--Group-1#6]

**Comment by savannahhoughtalin** [comment]
@Kelsey-little

**Comment by savannahhoughtalin** [comment]
Your topic is "frequency of types of extracurriculars people are involved in!"

**Comment by shelbypinette** [comment]
@Kelsey-little notify me when you have completed

**Comment by Kelsey-little** [comment]
@shelbypinette Will do!

**Comment by Kelsey-little** [comment]
@shelbypinette Done!

**Comment by shelbypinette** [comment]
@Kelsey-little looks great!
