### ISSUE TITLE
Make Descriptive Table

### ISSUE THREAD

**Issue by savannahhoughtalin** [savannahhoughtalin/QMB-210--Group-1#8]

**Comment by savannahhoughtalin** [comment]
@madisonlenhart16

**Comment by savannahhoughtalin** [comment]
For the topics in the descriptive table, I would suggest doing: major, year, gender, in greek life/not in greek life, NPS score for work/life balance and for recommendation of joining greek life. Do whatever you think is best!

**Comment by shelbypinette** [comment]
@madisonlenhart16 notify me when you have completed

**Comment by madisonlenhart16** [comment]
@shelbypinette I finished the descriptive table. I will link it on the comment. Take a look at it and let me know if I need to fix anything 

[Descriptive Table.xlsx](https://github.com/savannahhoughtalin/QMB-210--Group-1/files/13045175/Descriptive.Table.xlsx)

**Comment by shelbypinette** [comment]
@madisonlenhart16 I think it looks great! I'm just gonna change the label of your tab to descriptive table #8 but besides that looks great
